<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KakaoCli.Win.Core\KakaoCli.Win.Core.csproj" />
    <ProjectReference Include="..\KakaoCli.Win.Data\KakaoCli.Win.Data.csproj" />
  </ItemGroup>
</Project>
